# Generated by Django 3.2.8 on 2021-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_alter_mealplan_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
