# Generated by Django 3.2.8 on 2021-10-31 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('planner', '0006_alter_mealplan_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='end_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='planner.mealplan'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_type', to='planner.mealtype'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to=settings.AUTH_USER_MODEL),
        ),
    ]
