# Generated by Django 3.2.8 on 2021-11-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20211031_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='start_date',
            new_name='day_1',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='end_date',
        ),
    ]
